public with sharing class AWSfileupoadforproductController {

   /* @AuraEnabled
    public static Boolean recordInsert (String fileName, String fileURL,String objKey){
        
        //Product__c pro= new Product__c();
        //pro.URL__c=fileURL;
       // pro.Object_Key__c=objKey;
        return true;                                        
    }

  
    @AuraEnabled(cacheable=false)
    public static void fetchExistingFileNames(string parentId) {    
    }*/
}