/**
* @File Name : SObjectFetcher.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : June 27, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | June 27, 2025 |   | Initial Version
**/

public with sharing class SObjectFetcher {
   
}